openapi: 3.0.0

info:
  title: Stage SIOY1M2 - REST API du site de vente en ligne
  description: |
    Une API REST sécurisée pour gérer les utilisateurs, les produits, les listes de souhaits et les historiques d'achats.
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Serveur local de développement

paths:
  /products:
    post:
      summary: Créer un nouveau produit
      description: Crée un nouveau produit dans la base de données
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
            example:
              name: "iPhone 15 Pro"
              price: 1199.99
              inStock: true
              description: "Le dernier smartphone d'Apple avec puce A17 Pro"
      responses:
        "201":
          description: Produit créé avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Erreur serveur
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    get:
      summary: Récupérer tous les produits
      description: Récupère la liste de tous les produits (sans description)
      tags:
        - Products
      responses:
        "200":
          description: Liste des produits récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductSummary"
        "500":
          description: Erreur serveur
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /products/{id}:
    get:
      summary: Récupérer un produit par ID
      description: Récupère les informations complètes d'un produit spécifique
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: ID du produit
          schema:
            type: string
            pattern: "^[0-9a-fA-F]{24}$"
            example: "507f1f77bcf86cd799439011"
      responses:
        "200":
          description: Produit trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Erreur serveur ou produit non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Mettre à jour un produit
      description: Met à jour les informations d'un produit existant
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: ID du produit à modifier
          schema:
            type: string
            pattern: "^[0-9a-fA-F]{24}$"
            example: "507f1f77bcf86cd799439011"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
            example:
              name: "iPhone 15 Pro Max"
              price: 1299.99
              inStock: false
              description: "Version mise à jour avec écran plus grand"
      responses:
        "200":
          description: Produit mis à jour avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Produit mis à jour avec succès"
        "500":
          description: Erreur serveur ou produit non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Supprimer un produit
      description: Supprime un produit de la base de données
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: ID du produit à supprimer
          schema:
            type: string
            pattern: "^[0-9a-fA-F]{24}$"
            example: "507f1f77bcf86cd799439011"
      responses:
        "200":
          description: Produit supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Produit supprimé avec succès"
        "500":
          description: Erreur serveur ou produit non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users:
    post:
      summary: Créer un nouvel utilisateur
      description: Crée un nouvel utilisateur dans la base de données
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
            example:
              name: "John Doe"
              email: "john.doe@example.com"
              password: "motdepasse123"
      responses:
        "201":
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          description: Erreur serveur
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    get:
      summary: Récupérer tous les utilisateurs
      description: Récupère la liste de tous les utilisateurs
      tags:
        - Users
      responses:
        "200":
          description: Liste des utilisateurs récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500":
          description: Erreur serveur
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users/{id}:
    get:
      summary: Récupérer un utilisateur par ID
      description: Récupère les informations d'un utilisateur spécifique
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: ID de l'utilisateur
          schema:
            type: string
            pattern: "^[0-9a-fA-F]{24}$"
            example: "507f1f77bcf86cd799439011"
      responses:
        "200":
          description: Utilisateur trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          description: Erreur serveur ou utilisateur non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Mettre à jour un utilisateur
      description: Met à jour les informations d'un utilisateur existant
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: ID de l'utilisateur à modifier
          schema:
            type: string
            pattern: "^[0-9a-fA-F]{24}$"
            example: "507f1f77bcf86cd799439011"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
            example:
              name: "John Doe Updated"
              email: "john.updated@example.com"
      responses:
        "200":
          description: Utilisateur mis à jour avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Utilisateur mis à jour avec succès"
        "500":
          description: Erreur serveur ou utilisateur non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Supprimer un utilisateur
      description: Supprime un utilisateur de la base de données
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: ID de l'utilisateur à supprimer
          schema:
            type: string
            pattern: "^[0-9a-fA-F]{24}$"
            example: "507f1f77bcf86cd799439011"
      responses:
        "200":
          description: Utilisateur supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Utilisateur supprimé avec succès"
        "500":
          description: Erreur serveur ou utilisateur non trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: ID unique de l'utilisateur (MongoDB ObjectId)
          example: "507f1f77bcf86cd799439011"
        name:
          type: string
          description: Nom complet de l'utilisateur
          example: "John Doe"
        email:
          type: string
          format: email
          description: Adresse email de l'utilisateur
          example: "john.doe@example.com"
        password:
          type: string
          description: Mot de passe de l'utilisateur
          example: "motdepasse123"
      required:
        - name
        - email
        - password

    UserInput:
      type: object
      properties:
        name:
          type: string
          description: Nom complet de l'utilisateur
          example: "John Doe"
        email:
          type: string
          format: email
          description: Adresse email de l'utilisateur
          example: "john.doe@example.com"
        password:
          type: string
          description: Mot de passe de l'utilisateur
          example: "motdepasse123"
      required:
        - name
        - email
        - password

    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID unique du produit (MongoDB ObjectId)
          example: "507f1f77bcf86cd799439011"
        name:
          type: string
          description: Nom du produit
          example: "iPhone 15 Pro"
        price:
          type: number
          format: float
          description: Prix du produit en euros
          example: 1199.99
        inStock:
          type: boolean
          description: Disponibilité du produit en stock
          example: true
        description:
          type: string
          description: Description détaillée du produit
          example: "Le dernier smartphone d'Apple avec puce A17 Pro"
      required:
        - name
        - price
        - inStock

    ProductSummary:
      type: object
      properties:
        _id:
          type: string
          description: ID unique du produit (MongoDB ObjectId)
          example: "507f1f77bcf86cd799439011"
        name:
          type: string
          description: Nom du produit
          example: "iPhone 15 Pro"
        price:
          type: number
          format: float
          description: Prix du produit en euros
          example: 1199.99
        inStock:
          type: boolean
          description: Disponibilité du produit en stock
          example: true
      required:
        - name
        - price
        - inStock

    ProductInput:
      type: object
      properties:
        name:
          type: string
          description: Nom du produit
          example: "iPhone 15 Pro"
        price:
          type: number
          format: float
          description: Prix du produit en euros
          example: 1199.99
        inStock:
          type: boolean
          description: Disponibilité du produit en stock
          example: true
        description:
          type: string
          description: Description détaillée du produit
          example: "Le dernier smartphone d'Apple avec puce A17 Pro"
      required:
        - name
        - price
        - inStock

    Error:
      type: object
      properties:
        error:
          type: string
          description: Message d'erreur
          example: "Erreur lors de la récupération de l'utilisateur"
      required:
        - error

tags:
  - name: Users
    description: Opérations liées à la gestion des utilisateurs
  - name: Products
    description: Opérations liées à la gestion des produits
