openapi: 3.0.0

info:
	title: Stage SIOY1M2 - REST API du site de vente en ligne
	description: |
		Une API REST sécurisée pour gérer les utilisateurs, les produits, les listes de souhaits et les historiques d'achats.
	version: 1.0.0
	
servers:
	- url: http://localhost:3000
		description: Serveur local de développement
